config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'

  resources :users do
    resources :posts
  end

  resources :posts do
  end

  resources :categories do
    resources :posts
  end

  get '/signin', to: 'users#signin'
  post '/signin', to: 'users#signin!'
  get '/signup', to: 'users#signup'
  post '/signup', to: 'users#signup!'
  get '/signout', to: 'users#signout'

end

app/models/categories_post.rb
class CategoriesPost < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/categories_posts.rb
class CategoriesPosts < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :posts, through: :categorizations
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :categorizations, :dependent => :destroy
  has_many :categories, through: :categorizations
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate
  #come back later
  # before_action :authenticate, only: [:index]

  helper_method :current_user

  def current_user
    return User.find(session[:user_id])
  end

  private
  def authenticate
    # mms: indentation
    # mms: You should be able to just use `session[:user_id]` here, no need for an extra session entry.
    # mms:    I expect you'll find that these are both set at the same time.
    # mss:    Though, I do respect the the clarity of this key.
    if !session[:is_signed_in]
      redirect_to "/signin"
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # mms: this is already in ApplicationController, so it a before_action for ALL controllers (that inherit from ApplicationController).
  before_action :authenticate

  def index
    # mms: This code looks familiar - aren't we already finding the User from the session somwhere?
    @user = User.find(session[:user_id])
    if @user
      @posts = Post.all
      @categories = Category.all
    # else
      # mms: what should index do if there wasn't a current user?
    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate

  def index
    @category = Category.find(params[:category_id])
    # mms: don't you want the posts for the category you just retrieved?  Or is this carry-over from the previous implementation?
    @posts = Post.all
  end

  def new
    # mms: Due to the nested routes, I was expecting a category here.  If not, I recommend you adjust your routes using `only:` or `except:`
    @post = Post.new
  end

  def create
    @post = current_user.posts.create!(post_params)
    redirect_to post_path(@post)
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    # mms: we probably want to use `current_user.posts...` here too
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    # mms: we probably want to use `current_user.posts...` here too
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to categories_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :command, :description, :category_ids => [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate

  def index
    @users = User.all
    @user = user.find(params[:id])||current_user
  end

  def show
    @user = User.find(params[:id])
    @post = @user.posts
  end

  def signup
  end

  def signup!
    user = User.new(
      username: params[:username],
      password_digest: BCrypt::Password.create(params[:password])
    )
    if params[:password_confirmation] != params[:password]
      message = "Your passwords don't match."
    elsif user.save
      message = "Your account has been created. Now please sign in."
    else
      message = "Your account couldn't be created. Did you enter a unique username and password?"
    end
    puts message
    flash[:notice] = message
    redirect_to action: :signin!
  end

  def signin
  end

  def signin!
    @user = User.find_by(username: params[:username])
    if !@user
      message = "This user doesn't exist. Please sign up."
    elsif !BCrypt::Password.new(@user.password_digest).is_password?(params[:password])
      message = "Your password's wrong."
    else
      message = "You're signed in, #{@user.username}!"
      session[:is_signed_in] = true
      session[:user_id] = @user.id
      cookies[:username] = {
      value: @user.username,
      expires: 1.year.from_now
    }
    end
    flash[:notice] = message
    redirect_to root_url
  end

  def signin_prompt
  end

  def signout
    flash[:notice] = "You're signed out."
    reset_session
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="header">
  <h3 class="text-center">DEVELOPER COMMAND HACKS ALLOWS YOU TO LEARN NEW SHORTCUTS EVERYDAY</h3>
  <h4 class="text-center">Click on a category and start learning.</h4>
  <h4 class="text-center">These hacks will definitely shave valuable seconds from a developer's life.</h4>
</div>

<!-- <div id="slider">
  <a href="#" class="control_next"> > </a>
  <a href="#" class="control_prev"> < </a>
  <ul>
    <li>
      <h2>Copy Highlighted Text</h2>
      <p>Beginner</p>
      <p>cmd-c</p>
      <p>Copy highlighted text with this command.</p>
    </li>
    <li>
      <h2>Paste Highlighted Text</h2>
      <p>Beginner</p>
      <p>cmd-p</p>
      <p>Paste highlighted text with this command.</p>
    </li>
    <li>
      <h2>Close Tab Easily</h2>
      <p>Atom</p>
      <p>cmd-w</p>
      <p>Close a tab without trying to find the little X.</p>
    </li>
  </ul>
</div> -->

<nav class="categories">
  <% @categories.each do |category| %>
    <h4 class="text-center">
      <%= link_to category.name.upcase, category_posts_path(category) %>
      <p>Click on this category<br>and learn cool new commands<br>for <%=category.name%>.</p>
    </h4>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Developer Command Hacks</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <link href='//fonts.googleapis.com/css?family=Josefin+Sans:400,600,700italic' rel='stylesheet' type='text/css'>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Developer Command Hacks</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", categories_path, class: "home" %></li>
        <li><%= link_to "Create Command", new_post_path, class: "create" %></li>
        <li>
          <% if @user %>
          <%= link_to "My Commands", user_path(@user), class: "my_command" %>
         <% end %>
       </li>
       <li>
         <% if session[:is_signed_in] %>
           <a href="/signout"><%= current_user.username %>: Sign Out</a>
        </li>
        <li>
         <% else %>
           <a href="/signup">Sign Up</a>
        </li>
        <li>
           <a href="/signin"> Sign In</a>
         <% end %>
       </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
<form class="form-horizontal">

  <div class="form-group">
    <label class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <%= collection_check_boxes(:post, :category_ids, Category.all, :id, :name) %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Command</label>
    <div class="col-sm-10">
      <%= f.text_field :command, :class => "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
      <%= f.text_field :description, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>

</form>
<% end %>

app/views/posts/edit.html.erb
<h2> Edit Post </h2>

<%= render partial: "form" %>

<%= form_for [@post], method: :delete do |f| %>
<%= f.submit "Delete Post", class: "delete" %>

<% end %>

app/views/posts/index.html.erb
<table class="table table-striped">
  <tr>
    <th>Command Title</th>
  </tr>
<% @category.posts.each do |post| %>
  <tr>
    <tc>
      <td>
        <%= link_to "#{post.title}", post_path(post) %>
      </td>
    </tc>
  </tr>
<% end %>
</table>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render partial: "form" %>

app/views/posts/show.html.erb
<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Command</th>
    <th>Description</th>
  </tr>
  <tr>
    <tc>
      <td>
        <%= @post.title %>
        <% if @post.user_id == current_user.id %>
        <%= link_to "(Edit)", edit_post_path(@post) %>
        <% end %>
      </td>
    </tc>
    <tc>
      <td>
        <%= @post.command %>
      </td>
    </tc>
    <tc>
      <td>
        <%= @post.description %>
      </td>
    </tc>
  </tr>
</table>

app/views/users/show.html.erb
<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Command</th>
    <th>Description</th>
  </tr>
    <% @user.posts.each do |post| %>
    <tr>
      <tc>
        <td>
          <%= link_to "#{post.title}", post_path(post) %>
        </td>
      </tc>
      <tc>
        <td>
          <%= post.command %>
        </td>
      </tc>
      <tc>
        <td>
          <%= post.description %>
        </td>
      </tc>
    </tr>
  <% end %>
</table>

app/views/users/signin.html.erb
<%= form_tag("/signin", method: "post") do %>
<form class="form-horizontal">
  <div class="form-group">
    <label class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
      <input type="text" name="username" class="form-control" placeholder="Username" value="<%= cookies[:username] %>">
    </div>
  </div>

  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign In</button>
    </div>
  </div>
</form>
<% end %>
<div class="flash_notice"><%= flash[:notice] %></div>

app/views/users/signin_prompt.html.erb
<h1> <%= link_to "Home", posts_path %>

<h2> <%= flash[:sign_in_message] %> </h2>
<%= form_tag("/signin", method: "post") do %>
<input type="text" name="username" placeholder="username" value="<%= cookies[:username] %>" />
<input type="password" name="password" placeholder="password"/>
<input type="submit" value="Sign in"/>
<% end %>

<!-- <h2> <%= flash[:sign_in_message] %> </h2>

<%=form_for :user, url: '/signin' do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Sign Up" %>
<% end %> -->

app/views/users/signup.html.erb
<%= form_tag("/signup", method: "post") do %>
<form class="form-horizontal">
  <div class="form-group">
    <label class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
      <input type="text" name="username" class="form-control" placeholder="Username">
    </div>
  </div>

  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>

  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input type="password" name="password_confirmation" class="form-control" id="inputPassword3" placeholder="Password Again">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign Up</button>
    </div>
  </div>
</form>
<% end %>
<div class="flash_notice"><%= flash[:notice] %></div>